dashM/urls.py
from django.urls import path
from . import views

app_name = "dashM"

urlpatterns = [
	path('', views.dashboard, name = 'manager'),
	path('accept/<int:pk>/', views.task_accept, name='task_accept'),
	path('reject/<int:pk>/', views.task_reject, name='task_reject'),
	path('delete/<int:pk>/', views.task_delete, name='task_delete')
]

tk1/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

from .views import index

# views
from team import views as team_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name = 'index'),
    path('login/',include('account.urls')),
    path('dashboard/', team_views.dashboard),
    # path('task/', include('task.urls')),
    path('', index, name = 'home'),
    path('teams/', team_views.dashboard, name='teams'),
    path('create-team/', team_views.create_team, name='create-team'),
    path('delete-team/<int:pk>/', team_views.delete_team, name='delete-team'),
    path('ajax-add-team/', team_views.add_team, name='ajax-add-team'),
    path('login/',include('account.urls', namespace='auth')),
    path('team/<int:id>/task/', include('task.urls', namespace="team")),
    path('team/<int:id>/chat/', include('chat.urls', namespace='chat')),
    path('dashM/<int:id>/', include('dashM.urls', namespace='manager'))
]

dashM/models.py
from django.db import models

# Create your models here.

dashM/views.py
from django.shortcuts import render, redirect
from task.models import Task
from task.forms import TaskForm
from team.models import Team
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest

# Create your views here.

@csrf_exempt

def dashboard(request, id) :
    if request.method == 'GET':
        taskOn = Task.objects.filter(team = Team.objects.get(id=id)).filter(status = 'on_going')
        taskSub = Task.objects.filter(team = Team.objects.get(id=id)).filter(status = 'submitted')
        team_instance = Team.objects.get(id=id)
        members = team_instance.members.all()
        
        response = {
            "task_On": taskOn,
            "task_Sub": taskSub,
            "team": team_instance,
            "member_list": members,
            "team_id" : id,
        }
        return render(request,'dashMn.html', response)
    else :
        return HttpResponseBadRequest('Bad request')

def task_accept(request, id, pk) :
    if request.method == 'GET' :
        task = Task.objects.filter(team = Team.objects.get(id=id)).get(id=pk)
        task.status = 'accepted'
        task.save()
        return redirect(f'/dashM/{id}')

def task_reject(request, id, pk) :
    if request.method == 'GET' :
        task = Task.objects.filter(team = Team.objects.get(id=id)).get(id=pk)
        task.status = 'on_going'
        task.save()
        return redirect(f'/dashM/{id}')

def task_delete(request, id, pk) :
    if request.method == 'GET' :
        task = Task.objects.filter(team = Team.objects.get(id=id)).get(id=pk)
        task.delete()
        return redirect(f'/dashM/{id}')

dashM/templates/dashMn.html
{% extends 'base.html' %}

{% block extra_headers %}
{% load static %}
    <link rel="stylesheet" href="{% static './dashM/dashMn.css' %}">
{% endblock %}

{% block body %}
<div class="content">
  <div class="container">
    <div class="members">
      <h1 class="team">{{ team.name }}</h1>
      <div class="members-list">
        {% for member in member_list %}
        <div class="member">{{member.username|slice:"0:1"}}</div>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="list-tasks">
    <div class="d-flex justify-content-end p-2">
      <a href="{% url 'delete-team' team.pk %}" class="badge badge-pill badge-danger" style="cursor: pointer;">Delete Team</a>
    </div>
    <div class="container p-4 mb-2 text-center text-dark">
      <a href="/team/{{ team_id }}/task/add/">
        <button type="button" class="btn btn-light btn-outline-success btn-lg">Add Task</button>
      </a>
    </div>
    <div class="container">
      <h3>Submitted Task :</h3>
      <br>
      {% if task_Sub|length == 0 %}
        <div class="alert alert-primary" role="alert">
          No Tasks Submitted
        </div>
      {% endif %}
    </div>
    {% for i in task_Sub %}
    <div class="container mb-3">
      <ul class="nav">
          {% csrf_token %}
          <li class="nav-item">
          <a class="nav-link text-dark" href="{% url 'dashM:task_accept' id=team_id pk=i.id %}">Accept</a>
          </li>
          {% csrf_token %}
          <li class="nav-item">
          <a class="nav-link text-danger" href="{% url 'dashM:task_reject' id=team_id pk=i.id %}">Reject</a>
          </li>
      </ul>
      <h4><i>Task {{i.id}}</i> : {{i.task_name}}</h4>
    </div>

    <div class="container list-task">
      <div style="background-color: white;" class="jumbotron jumbotron-fluid shadow">
        <div class="container">
          <p class="lead">{{ i.description }} </p>
          <div class="card border-dark mb-3" style="max-width: 35rem;">
            <div class="card text-dark" style="background-color: #f1f1f1;">
              <p class="card-text p-2">Submitted by: {{ i.member }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}


    <div class="container">
      <h3>On-going Task :</h3>
      <br>
      {% if task_On|length == 0 %}
        <div class="alert alert-primary" role="alert">
          No On-going Tasks
        </div>
      {% endif %}
    </div>
    {% for i in task_On %}
    <div class="container mb-3">
      <ul class="nav">
        {% csrf_token %}
        <li class="nav-item">
        <a class="nav-link text-danger" href="{% url 'dashM:task_delete' id=team_id pk=i.id %}">Delete Task</a>
        </li>
      </ul>
      <h4><i>Task {{i.id}}</i> : {{i.task_name}}</h4>
    </div>

    <div class="container list-task">
      <div style="background-color: white;" class="jumbotron jumbotron-fluid shadow">
        <div class="container">
          <p class="lead">{{ i.description }} </p>
          <div class="card border-dark mb-3" style="max-width: 35rem;">
            <div class="card text-dark" style="background-color: #f1f1f1;">
              <p class="card-text p-2">Given to: {{ i.member }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

</div>






<!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
{% endblock %}